#! /bin/bash

# Script for monitoring the line-in with Pulseaudio

DELAY="1" # delay in ms
INPUT="alsa_input.pci-0000_00_1b.0.analog-stereo"
OUTPUT="alsa_output.pci-0000_05_01.0.analog-stereo"

pacat -r --latency-msec=$DELAY -d "$INPUT" | pacat -p  \
	--latency-msec=$DELAY -d "$OUTPUT"
