#! /bin/sh

# Small script for controlling Spotify Linux
# Tested with Spotify 0.6.6

NAME="Spotify Premium"
D="org.mpris.MediaPlayer2.spotify"
P="/org/mpris/MediaPlayer2"

if [ "$1" = "next" ] ; then
	MSG="org.mpris.MediaPlayer2.Player.Next"
	dbus-send --print-reply --dest="$D" "$P" "$MSG" &> /dev/null
elif [ "$1" = "prev" ] ; then
	MSG="org.mpris.MediaPlayer2.Player.Previous"
	dbus-send --print-reply --dest="$D" "$P" "$MSG" &> /dev/null
elif [ "$1" = "toggle" ] ; then
	MSG="org.mpris.MediaPlayer2.Player.PlayPause"
	dbus-send --print-reply --dest="$D" "$P" "$MSG" &> /dev/null
elif [ "$1" = "np" ] ; then
echo `dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 2 "artist"|egrep -v "artist"|egrep -v "array"|cut -b 27-|cut -d '"' -f 1|egrep -v ^$` "-" `dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 1 "title"|egrep -v "title"|cut -b 44-|cut -d '"' -f 1|egrep -v ^$`
else
	echo "Usage: $0 [prev|next|toggle]"
fi
