#! /bin/sh

# Small script for controlling Spotify Linux
# Tested with Spotify 0.6.6

NAME="Spotify Premium"
D="org.mpris.MediaPlayer2.spotify"
P="/org/mpris/MediaPlayer2"

if [ "$1" = "next" ] ; then
	MSG="org.mpris.MediaPlayer2.Player.Next"
	dbus-send --print-reply --dest="$D" "$P" "$MSG" &> /dev/null
elif [ "$1" = "prev" ] ; then
	MSG="org.mpris.MediaPlayer2.Player.Previous"
	dbus-send --print-reply --dest="$D" "$P" "$MSG" &> /dev/null
elif [ "$1" = "toggle" ] ; then
	MSG="org.mpris.MediaPlayer2.Player.PlayPause"
	dbus-send --print-reply --dest="$D" "$P" "$MSG" &> /dev/null
else
	echo "Usage: $0 [prev|next|toggle]"
fi
